spring:
  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    driverClassName: org.h2.Driver
    password: '123456789'
    username: sa
    url: jdbc:h2:mem:pokedex
  h2:
    console:
      settings:
        trace: 'false'
        web-allow-others: 'false'
      path: /h2-console
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
graphql:
  servlet:
    mapping: /graphql
    corsEnabled: 'true'
    enabled: 'true'
